#!/usr/bin/env python3
# @spec [Doc-05A_V1.0, §6 / §12 / §12.4a] | @implemented [2026-06-10]
# plain English: the INDEPENDENT Python reference implementation of the V1.0 mastery
#   formula, and the canonical encoding of the 31 stress-test fixtures (B1-B23, S1-S8)
#   from Doc 05A §12. Per Doc 05A §12.4a (RB-05A-V1-13 / MED3) the expected fixture
#   values MUST be generated by an independent Python reference, NOT by the SQL function
#   in §6. This file IS that reference. The PL/pgSQL `compute_mastery_for_entity` is then
#   required to match this reference bit-for-bit within the §12.4 tolerances.
#
#   This file intentionally hard-codes the LOCKED constants from Doc 05 Parent §10.1.
#   That is by design (§12.4a: "Reads only the locked constants from Parent §10.1, no DB
#   dependency"): the reference must be an INDEPENDENT source of truth that does not read
#   the DB-seeded `mastery_constants`. The no-hardcoded-constants CI guard therefore
#   excludes scripts/reference/ (it gates engine/service code, not the reference oracle).
#
# expected outcome: `--selfcheck` recomputes all 31 fixtures and asserts they equal the
#   §12-published expected values (proving the reference matches the spec table);
#   `--emit-json PATH` writes the fixtures + reference outputs for the SQL parity harness.
# trade-offs: float64 position weights (§12.4a mandates `0.5 ** ((pos-1)/30)`); the SQL
#   side uses numeric POWER — agreement is within the §12.4 tolerances (acc ±1e-6,
#   score ±1e-4, pct ±0.01, level exact), which the three-way comparator enforces.
# edge cases: cold-start (0 events) and below-threshold (<5) return NULL per §6 Step 3;
#   easy-cap via min(1.0, ...); macro-average renormalizes over PRESENT sources only.

from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal, ROUND_HALF_UP
from typing import Optional, TypedDict

# ---------------------------------------------------------------------------
# Locked constants — Doc 05 Parent §10.1 (V1.0). Mirrors the DB-seeded
# mastery_constants in supabase/migrations/20260610010000_ws3_mastery_formula.sql.
# The reference is an INDEPENDENT oracle, so it carries the locked values directly.
# ---------------------------------------------------------------------------
POSITION_HALF_LIFE = 30.0
MIN_EVENTS_FOR_MASTERY = 5
WEIGHT_SOURCE = {"test": 0.50, "practice": 0.30, "review": 0.20}
DIFFICULTY_WEIGHT = {1: 0.79, 2: 1.0, 3: 1.20}  # 1=easy, 2=medium, 3=hard
MASTERY_MIN = 0.0
MASTERY_MAX = 1.0
LEVEL_BOUNDARIES = (0.20, 0.40, 0.60, 0.80)  # L1_min, L2_min, L3_min, L4_min
ROUND_SCORE_DECIMALS = 4
ROUND_PCT_DECIMALS = 2
ROUND_ACC_DECIMALS = 6

_DIFF_LETTER = {"E": 1, "M": 2, "H": 3}


class Event(TypedDict):
    source_family: str  # 'test' | 'practice' | 'review'
    difficulty: int     # 1 | 2 | 3
    correct: bool


class MasteryResult(TypedDict):
    total_events: int
    acc_test: Optional[float]
    acc_practice: Optional[float]
    acc_review: Optional[float]
    mastery_score: Optional[float]
    mastery_pct: Optional[float]
    mastery_level: Optional[int]


def _round_half_up(value: float, decimals: int) -> float:
    """Round-half-away-from-zero to `decimals`, matching PostgreSQL ROUND(numeric, n).
    All formula values are non-negative, so HALF_UP == round-half-away-from-zero here."""
    q = Decimal(1).scaleb(-decimals)  # 10**-decimals
    return float(Decimal(repr(value)).quantize(q, rounding=ROUND_HALF_UP))


def _lookup_level(score: float) -> int:
    # Doc 05A §6.3 half-open intervals: each level covers [min, next_min).
    l1, l2, l3, l4 = LEVEL_BOUNDARIES
    if score < l1:
        return 0
    if score < l2:
        return 1
    if score < l3:
        return 2
    if score < l4:
        return 3
    return 4


def compute_mastery(events: list[Event]) -> MasteryResult:
    """Doc 05A §6 formula, independent reference.

    Positions are assigned GLOBALLY over all the entity's events by recency
    (most-recent = position 1), exactly as the SQL ROW_NUMBER() OVER (ORDER BY
    occurred_at DESC, event_id DESC). The caller supplies `events` already in
    recency order (index 0 = most recent). acc_source is offset-invariant for a
    source occupying a contiguous position block (the §12 fixtures are authored
    that way), so per-source positions coincide with the global ones.
    """
    total = len(events)

    # Step 3 (early): cold-start / below-threshold → NULL.
    if total < MIN_EVENTS_FOR_MASTERY:
        return MasteryResult(
            total_events=total, acc_test=None, acc_practice=None, acc_review=None,
            mastery_score=None, mastery_pct=None, mastery_level=None,
        )

    # Step 2: global position (1-based), position weight, per-source weighted accuracy.
    num: dict[str, float] = {}
    den: dict[str, float] = {}
    for idx, ev in enumerate(events):
        pos = idx + 1
        pos_w = 0.5 ** ((pos - 1) / POSITION_HALF_LIFE)
        d_w = DIFFICULTY_WEIGHT[ev["difficulty"]]
        src = ev["source_family"]
        num[src] = num.get(src, 0.0) + d_w * pos_w * (1 if ev["correct"] else 0)
        den[src] = den.get(src, 0.0) + pos_w

    def acc(src: str) -> Optional[float]:
        if src not in den or den[src] == 0:
            return None
        return min(1.0, num[src] / den[src])

    acc_test = acc("test")
    acc_practice = acc("practice")
    acc_review = acc("review")

    # Step 4: macro-average across PRESENT sources, renormalized.
    weighted_sum = 0.0
    weight_sum = 0.0
    for src, a in (("test", acc_test), ("practice", acc_practice), ("review", acc_review)):
        if a is not None:
            weighted_sum += WEIGHT_SOURCE[src] * a
            weight_sum += WEIGHT_SOURCE[src]
    raw = weighted_sum / weight_sum  # weight_sum > 0 since total >= 5 implies a source present

    # Step 5: clamp + round; pct from rounded score; level from rounded score.
    score = _round_half_up(min(MASTERY_MAX, max(MASTERY_MIN, raw)), ROUND_SCORE_DECIMALS)
    pct = _round_half_up(100.0 * score, ROUND_PCT_DECIMALS)
    level = _lookup_level(score)

    # Step 6: round per-source accuracies for storage/report.
    return MasteryResult(
        total_events=total,
        acc_test=None if acc_test is None else _round_half_up(acc_test, ROUND_ACC_DECIMALS),
        acc_practice=None if acc_practice is None else _round_half_up(acc_practice, ROUND_ACC_DECIMALS),
        acc_review=None if acc_review is None else _round_half_up(acc_review, ROUND_ACC_DECIMALS),
        mastery_score=score,
        mastery_pct=pct,
        mastery_level=level,
    )


# ---------------------------------------------------------------------------
# The 31 canonical fixtures (Doc 05A §12.1 B1-B23 + §12.2 S1-S8).
# Each fixture event list is in RECENCY ORDER (index 0 = most recent = position 1).
# Multi-source fixtures lay each source out as a CONTIGUOUS block (recent-correct
# within the block); acc_source is offset-invariant so block order is immaterial.
# `block(src, letter, correct, n)` expands to n events.
# ---------------------------------------------------------------------------
def _block(src: str, letter: str, correct: bool, n: int) -> list[Event]:
    return [Event(source_family=src, difficulty=_DIFF_LETTER[letter], correct=correct) for _ in range(n)]


def _alternating(n: int) -> list[Event]:
    # B10: (prac,M,✓),(prac,M,✗),… — position 1 correct, 2 wrong, alternating.
    out: list[Event] = []
    for i in range(n):
        out.append(Event(source_family="practice", difficulty=2, correct=(i % 2 == 0)))
    return out


# expected values transcribed VERBATIM from Doc 05A §12.1 / §12.2 tables.
FIXTURES: dict[str, dict] = {
    "B1":  {"desc": "Cold start (zero events)", "events": [],
            "expected": {"total": 0, "acc_test": None, "acc_practice": None, "acc_review": None, "score": None, "pct": None, "level": None}},
    "B2":  {"desc": "Below threshold: 4 medium practice correct", "events": _block("practice", "M", True, 4),
            "expected": {"total": 4, "acc_test": None, "acc_practice": None, "acc_review": None, "score": None, "pct": None, "level": None}},
    "B3":  {"desc": "At threshold: 5 medium practice correct", "events": _block("practice", "M", True, 5),
            "expected": {"total": 5, "acc_test": None, "acc_practice": 1.000000, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B4":  {"desc": "5 hard test correct (only source)", "events": _block("test", "H", True, 5),
            "expected": {"total": 5, "acc_test": 1.000000, "acc_practice": None, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B5":  {"desc": "5 easy practice correct (easy cap)", "events": _block("practice", "E", True, 5),
            "expected": {"total": 5, "acc_test": None, "acc_practice": 0.790000, "acc_review": None, "score": 0.7900, "pct": 79.00, "level": 3}},
    "B6":  {"desc": "5 easy practice wrong", "events": _block("practice", "E", False, 5),
            "expected": {"total": 5, "acc_test": None, "acc_practice": 0.000000, "acc_review": None, "score": 0.0000, "pct": 0.00, "level": 0}},
    "B7":  {"desc": "10 medium practice all correct", "events": _block("practice", "M", True, 10),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 1.000000, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B8":  {"desc": "10 easy practice all correct (easy cap with volume)", "events": _block("practice", "E", True, 10),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 0.790000, "acc_review": None, "score": 0.7900, "pct": 79.00, "level": 3}},
    "B9":  {"desc": "10 hard practice all correct", "events": _block("practice", "H", True, 10),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 1.000000, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B10": {"desc": "10 medium practice 50% alternating", "events": _alternating(10),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 0.505776, "acc_review": None, "score": 0.5058, "pct": 50.58, "level": 2}},
    "B11": {"desc": "10 medium, recent 5 correct, old 5 wrong", "events": _block("practice", "M", True, 5) + _block("practice", "M", False, 5),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 0.528849, "acc_review": None, "score": 0.5288, "pct": 52.88, "level": 2}},
    "B12": {"desc": "10 medium, recent 5 wrong, old 5 correct", "events": _block("practice", "M", False, 5) + _block("practice", "M", True, 5),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 0.471151, "acc_review": None, "score": 0.4712, "pct": 47.12, "level": 2}},
    "B13": {"desc": "100 medium, recent 50 correct, old 50 wrong", "events": _block("practice", "M", True, 50) + _block("practice", "M", False, 50),
            "expected": {"total": 100, "acc_test": None, "acc_practice": 0.760468, "acc_review": None, "score": 0.7605, "pct": 76.05, "level": 3}},
    "B14": {"desc": "100 medium, recent 50 wrong, old 50 correct", "events": _block("practice", "M", False, 50) + _block("practice", "M", True, 50),
            "expected": {"total": 100, "acc_test": None, "acc_practice": 0.239532, "acc_review": None, "score": 0.2395, "pct": 23.95, "level": 1}},
    "B15": {"desc": "Inactivity: 5 hard test correct months ago", "events": _block("test", "H", True, 5),
            "expected": {"total": 5, "acc_test": 1.000000, "acc_practice": None, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B16": {"desc": "Realistic mixed",
            "events": _block("test", "H", True, 3) + _block("test", "H", False, 2)
                      + _block("practice", "M", True, 7) + _block("practice", "M", False, 3)
                      + _block("review", "E", True, 2) + _block("review", "E", False, 1),
            "expected": {"total": 18, "acc_test": 0.736567, "acc_practice": 0.723864, "acc_review": 0.532727, "score": 0.6920, "pct": 69.20, "level": 3}},
    "B17": {"desc": "10 hard test 80% (only source)", "events": _block("test", "H", True, 8) + _block("test", "H", False, 2),
            "expected": {"total": 10, "acc_test": 0.981653, "acc_practice": None, "acc_review": None, "score": 0.9817, "pct": 98.17, "level": 4}},
    "B18": {"desc": "Volume invariance baseline: 10 medium correct", "events": _block("practice", "M", True, 10),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 1.000000, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B19": {"desc": "Volume invariance check: 500 medium correct", "events": _block("practice", "M", True, 500),
            "expected": {"total": 500, "acc_test": None, "acc_practice": 1.000000, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B20": {"desc": "All perfect hard: 5 test + 20 practice + 10 review",
            "events": _block("test", "H", True, 5) + _block("practice", "H", True, 20) + _block("review", "H", True, 10),
            "expected": {"total": 35, "acc_test": 1.000000, "acc_practice": 1.000000, "acc_review": 1.000000, "score": 1.0000, "pct": 100.00, "level": 4}},
    "B21": {"desc": "70% on hard practice", "events": _block("practice", "H", True, 7) + _block("practice", "H", False, 3),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 0.868637, "acc_review": None, "score": 0.8686, "pct": 86.86, "level": 4}},
    "B22": {"desc": "70% on easy practice (easy cap with mixed accuracy)", "events": _block("practice", "E", True, 7) + _block("practice", "E", False, 3),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 0.571853, "acc_review": None, "score": 0.5719, "pct": 57.19, "level": 2}},
    "B23": {"desc": "All wrong: 10 medium practice", "events": _block("practice", "M", False, 10),
            "expected": {"total": 10, "acc_test": None, "acc_practice": 0.000000, "acc_review": None, "score": 0.0000, "pct": 0.00, "level": 0}},
    # --- sparse-test scenarios S1-S8 (§12.2) ---
    "S1":  {"desc": "5 test correct + 5 practice wrong", "events": _block("test", "M", True, 5) + _block("practice", "M", False, 5),
            "expected": {"total": 10, "acc_test": 1.000000, "acc_practice": 0.000000, "acc_review": None, "score": 0.6250, "pct": 62.50, "level": 3}},
    "S2":  {"desc": "5 test wrong + 5 practice correct", "events": _block("test", "M", False, 5) + _block("practice", "M", True, 5),
            "expected": {"total": 10, "acc_test": 0.000000, "acc_practice": 1.000000, "acc_review": None, "score": 0.3750, "pct": 37.50, "level": 1}},
    "S3":  {"desc": "5 hard test correct + 50 medium practice 50%",
            "events": _block("test", "H", True, 5) + _block("practice", "M", True, 25) + _block("practice", "M", False, 25),
            "expected": {"total": 55, "acc_test": 1.000000, "acc_practice": 0.640520, "acc_review": None, "score": 0.8652, "pct": 86.52, "level": 4}},
    "S4":  {"desc": "5 hard test 60% + 50 medium practice 80%",
            "events": _block("test", "H", True, 3) + _block("test", "H", False, 2)
                      + _block("practice", "M", True, 40) + _block("practice", "M", False, 10),
            "expected": {"total": 55, "acc_test": 0.736567, "acc_practice": 0.880485, "acc_review": None, "score": 0.7905, "pct": 79.05, "level": 3}},
    "S5":  {"desc": "Mixed perfect: 5 hard test + 5 easy practice + 5 medium review",
            "events": _block("test", "H", True, 5) + _block("practice", "E", True, 5) + _block("review", "M", True, 5),
            "expected": {"total": 15, "acc_test": 1.000000, "acc_practice": 0.790000, "acc_review": 1.000000, "score": 0.9370, "pct": 93.70, "level": 4}},
    "S6":  {"desc": "Single-source test: 5 medium test correct", "events": _block("test", "M", True, 5),
            "expected": {"total": 5, "acc_test": 1.000000, "acc_practice": None, "acc_review": None, "score": 1.0000, "pct": 100.00, "level": 4}},
    "S7":  {"desc": "Single-source review: 5 medium review correct", "events": _block("review", "M", True, 5),
            "expected": {"total": 5, "acc_test": None, "acc_practice": None, "acc_review": 1.000000, "score": 1.0000, "pct": 100.00, "level": 4}},
    "S8":  {"desc": "Sparse multi-source low-volume: 1 test + 1 practice + 3 review",
            "events": _block("test", "M", True, 1) + _block("practice", "M", True, 1) + _block("review", "M", True, 3),
            "expected": {"total": 5, "acc_test": 1.000000, "acc_practice": 1.000000, "acc_review": 1.000000, "score": 1.0000, "pct": 100.00, "level": 4}},
}


def _acc_close(a: Optional[float], b: Optional[float], tol: float) -> bool:
    if a is None or b is None:
        return a is None and b is None
    return abs(a - b) <= tol


def _selfcheck() -> int:
    """Recompute each fixture and assert it matches the §12-published expected values.
    Proves: Python reference == Doc 05A §12 table. Tolerances per §12.4."""
    failures: list[str] = []
    for fid, fx in FIXTURES.items():
        got = compute_mastery(fx["events"])
        exp = fx["expected"]
        checks = [
            ("total", got["total_events"] == exp["total"]),
            ("acc_test", _acc_close(got["acc_test"], exp["acc_test"], 1e-6)),
            ("acc_practice", _acc_close(got["acc_practice"], exp["acc_practice"], 1e-6)),
            ("acc_review", _acc_close(got["acc_review"], exp["acc_review"], 1e-6)),
            ("score", _acc_close(got["mastery_score"], exp["score"], 1e-4)),
            ("pct", _acc_close(got["mastery_pct"], exp["pct"], 1e-2)),
            ("level", got["mastery_level"] == exp["level"]),
        ]
        bad = [name for name, ok in checks if not ok]
        if bad:
            failures.append(f"{fid} ({fx['desc']}): mismatched {bad}\n    got={got}\n    exp={exp}")
    if failures:
        print("REFERENCE SELF-CHECK FAILED — Python reference does not match Doc 05A §12:")
        for f in failures:
            print("  - " + f)
        return 1
    print(f"REFERENCE SELF-CHECK PASSED — all {len(FIXTURES)} fixtures match Doc 05A §12 (B1-B23, S1-S8).")
    return 0


def _emit_json(path: str) -> int:
    """Emit fixtures (events in recency order) + reference outputs as JSON for the
    SQL parity harness. The harness loads the SAME event sets into a fixture-backed
    canonical_mastery_events and compares SQL output three-way."""
    out = {}
    for fid, fx in FIXTURES.items():
        got = compute_mastery(fx["events"])
        out[fid] = {
            "desc": fx["desc"],
            "events": fx["events"],   # recency order; index 0 == position 1
            "reference": got,
            "expected": fx["expected"],
        }
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2)
    print(f"wrote {len(out)} fixtures + reference outputs → {path}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Doc 05A V1.0 mastery formula — Python reference + fixtures")
    ap.add_argument("--selfcheck", action="store_true", help="assert reference == Doc 05A §12 expected")
    ap.add_argument("--emit-json", metavar="PATH", help="write fixtures + reference outputs to PATH")
    args = ap.parse_args()
    if args.emit_json:
        return _emit_json(args.emit_json)
    # default action is the self-check (the CI gate's first half).
    return _selfcheck()


if __name__ == "__main__":
    sys.exit(main())
