const stage=document.querySelector('#stage');
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));
const ease=n=>1-Math.pow(1-clamp(n),3);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const enter=(local,delay=.1,dur=.55)=>{const p=ease((local-delay)/dur);return `opacity:${p};transform:translateY(${(1-p)*34}px) scale(${.985+p*.015})`};
const brand=`<div class="brand">LYCEON</div>`;
function frame(t){
 let s,local;
 if(t<3.5){s=1;local=t}
 else if(t<7.5){s=2;local=t-3.5}
 else if(t<12.5){s=3;local=t-7.5}
 else if(t<16.5){s=4;local=t-12.5}
 else if(t<20){s=5;local=t-16.5}
 else{s=6;local=t-20}
 stage.innerHTML=render(s,local,t);
}
function render(s,l,t){
 if(s===1){const loop=clamp((l-1.15)/1.55);return `<section class="scene"><div class="topbar">${brand}<span class="pill">Digital SAT</span></div><div style="display:grid;grid-template-columns:1.05fr .95fr;gap:72px;align-items:center;flex:1"><div style="${enter(l,.1,.7)}"><div class="eyebrow">A connected learning system</div><h1 class="title">SAT prep shouldn’t feel random.</h1><p class="sub">Every answer should make the next move clearer.</p></div><div class="card" style="padding:36px;${enter(l,.55,.65)}"><div class="mini-label">Practice · Algebra</div><h2 style="font-size:31px;line-height:1.35;margin:18px 0 28px">If 3x + 5 = 26, what is the value of x?</h2><div class="grid" style="grid-template-columns:1fr 1fr;gap:14px"><div class="option">A&nbsp;&nbsp;5</div><div class="option">B&nbsp;&nbsp;6</div><div class="option selected">C&nbsp;&nbsp;7</div><div class="option">D&nbsp;&nbsp;8</div></div></div></div><div class="row" style="gap:16px;opacity:${clamp((l-.95)/.45)}">${['Baseline','Practice','Understand','Improve'].map((x,i)=>`<div class="node" style="opacity:${clamp((loop*4-i))}">${x}</div>${i<3?`<div class="line" style="--fill:${clamp(loop*4-i)}"></div>`:''}`).join('')}</div></section>`}
 if(s===2){const p=ease((l-.7)/1.1);return `<section class="scene"><div class="topbar">${brand}<div class="eyebrow">01 · Find the signal</div></div><div style="display:grid;grid-template-columns:.9fr 1.1fr;gap:58px;align-items:center;flex:1"><div class="card" style="padding:38px;${enter(l,.05,.55)}"><div class="mini-label">Diagnostic baseline complete</div><div class="row" style="gap:52px;margin:32px 0"><div><div class="metric">560</div><div class="muted">Math</div></div><div><div class="metric">610</div><div class="muted">Reading & Writing</div></div></div><div class="progress"><i style="width:${56*p}%"></i></div><div style="height:16px"></div><div class="progress"><i style="width:${61*p}%"></i></div></div><div style="${enter(l,.65,.65)}"><div class="eyebrow">Signal → next action</div><h1 class="title" style="font-size:66px">Start where progress can move.</h1><div class="card" style="padding:26px 30px;margin-top:28px"><div class="row" style="justify-content:space-between"><div><div class="mini-label">Recommended focus</div><div style="font-size:32px;font-weight:800;margin-top:7px">Linear equations</div></div><span class="button">Start focused practice →</span></div></div></div></div></section>`}
 if(s===3){const select=clamp((l-.35)/.3),result=clamp((l-1.25)/.35),explain=clamp((l-1.8)/.55),tutor=clamp((l-3.15)/.55);return `<section class="scene"><div class="topbar">${brand}<div class="eyebrow">02 · Practise. Understand.</div></div><div style="display:grid;grid-template-columns:1.05fr .95fr;gap:32px;flex:1;align-items:center"><div class="card" style="padding:32px;${enter(l,.05,.45)}"><div class="row" style="justify-content:space-between"><div class="mini-label">Focused practice · Linear equations</div><span class="pill">Question 3</span></div><h2 style="font-size:32px;line-height:1.38;margin:24px 0">If 3x + 5 = 26, what is the value of x?</h2><div class="grid" style="grid-template-columns:1fr 1fr;gap:12px"><div class="option">x = 5</div><div class="option">x = 6</div><div class="option selected" style="box-shadow:0 0 0 ${select*4}px rgba(15,46,72,.12)">x = 7</div><div class="option">x = 8</div></div><div class="row" style="justify-content:space-between;margin-top:22px"><span style="color:var(--green);font-size:24px;font-weight:800;opacity:${result}">✓ Correct</span><span class="button">Answer submitted</span></div></div><div style="display:flex;flex-direction:column;gap:18px"><div class="card" style="padding:28px;opacity:${explain};transform:translateY(${(1-explain)*28}px)"><div class="mini-label">Why it works</div><p style="font-size:23px;line-height:1.55;margin:14px 0 0">Subtract 5 from both sides, then divide by 3.<br><b>3x = 21 → x = 7</b></p></div><div class="card navy" style="padding:28px;opacity:${tutor};transform:translateY(${(1-tutor)*28}px)"><div class="mini-label" style="opacity:.7">Ask Lyceon · Question in context</div><p style="font-size:23px;margin:14px 0 0">“Show me why subtracting 5 keeps the equation balanced.”</p></div></div></div></section>`}
 if(s===4){const move=ease((l-.35)/1.1),bar=ease((l-1.1)/1.35),next=clamp((l-2.2)/.55);return `<section class="scene"><div class="topbar">${brand}<div class="eyebrow">03 · Turn answers into direction</div></div><div class="row" style="gap:42px;flex:1"><div class="card" style="padding:34px;width:480px;${enter(l,.05,.45)}"><div class="mini-label">Observed event</div><div class="row" style="gap:18px;margin-top:22px"><span class="eventdot"></span><div><b style="font-size:25px">Linear equations · Correct</b><div class="muted" style="margin-top:6px">Evidence, not a guess</div></div></div></div><div class="line" style="--fill:${move}"></div><div class="card" style="padding:34px;width:610px;${enter(l,.45,.5)}"><div class="row" style="justify-content:space-between"><div><div class="mini-label">Your mastery · Algebra</div><div style="font-size:35px;font-weight:800;margin-top:8px">Developing → Proficient</div></div><div class="check">✓</div></div><div class="progress" style="margin-top:28px;height:18px"><i style="width:${36+bar*38}%"></i></div></div></div><div class="card navy" style="padding:25px 32px;opacity:${next};transform:translateY(${(1-next)*24}px)"><div class="row" style="justify-content:space-between"><div><div class="mini-label">Your next milestone</div><div style="font-size:29px;font-weight:700;margin-top:7px">Complete one focused SAT practice block today.</div></div><span class="button" style="background:var(--cream);color:var(--navy)">Continue →</span></div></div></section>`}
 if(s===5){const locks=clamp((l-.6)/.7),guardian=clamp((l-1.25)/.65);const metrics=`<div class="grid" style="grid-template-columns:1fr 1fr;gap:18px"><div><div class="metric">24</div><div class="muted">Questions · 7d</div></div><div><div class="metric">83%</div><div class="muted">Accuracy · 7d</div></div></div><div style="margin-top:26px"><div class="mini-label">Domain mastery</div><div class="progress" style="margin-top:12px"><i style="width:72%"></i></div></div>`;return `<section class="scene"><div class="topbar">${brand}<div class="eyebrow">04 · Progress everyone can trust</div></div><div class="grid" style="grid-template-columns:1fr 160px 1fr;gap:28px;align-items:center;flex:1"><div class="card" style="padding:38px;${enter(l,.05,.5)}"><div class="row" style="justify-content:space-between;margin-bottom:30px"><div style="font-size:28px;font-weight:800">Student dashboard</div><span class="pill">Maya</span></div>${metrics}</div><div style="text-align:center;opacity:${locks}"><div class="check" style="margin:auto">✓</div><div class="line" style="margin:22px 0;--fill:${locks}"></div><div class="mini-label">Linked<br>+ entitled</div></div><div class="card" style="padding:38px;opacity:${guardian};transform:translateX(${(1-guardian)*40}px)"><div class="row" style="justify-content:space-between;margin-bottom:30px"><div style="font-size:28px;font-weight:800">Guardian view</div><span class="tag">VIEW ONLY</span></div>${metrics}</div></div><p class="sub" style="text-align:center;max-width:none;opacity:${guardian}">One student. One progress truth. Clear boundaries.</p></section>`}
 const p=ease((l-.1)/.8);return `<section class="scene navy" style="justify-content:center;align-items:center;text-align:center"><div style="opacity:${p};transform:scale(${.96+p*.04})"><div class="brand" style="font-size:34px">LYCEON</div><h1 class="title" style="font-size:88px;max-width:1200px;margin:34px auto 22px">Know what to practise next — and why.</h1><p class="sub" style="color:var(--cream);opacity:.72;margin:0 auto 46px">Diagnostic → focused practice → understanding → measured mastery.</p><span class="button" style="display:inline-block;background:var(--cream);color:var(--navy);padding:20px 34px">Start free practice</span></div><div class="row" style="position:absolute;bottom:74px;gap:14px;opacity:${clamp((l-1.5)/.6)}">${['Baseline','Practice','Understand','Improve'].map((x,i)=>`<span class="pill" style="color:var(--cream);border-color:rgba(255,250,239,.3);background:transparent">${esc(x)}</span>${i<3?'<span style="opacity:.5">→</span>':''}`).join('')}</div></section>`
}
const q=new URLSearchParams(location.search);frame(Number(q.get('t')||21.8));window.renderAt=frame;
