import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: "var(--radius)",
        lg: "calc(var(--radius) + 2px)",
        xl: "calc(var(--radius) + 6px)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        /* Brand colors - ONLY Cream + Navy */
        'brand-cream': '#FFFAEF',
        'brand-surface': '#F9F3E7',
        'brand-navy': '#0F2E48',
        
        /* Student UI design tokens (register UI-40, UI-47): student-tokens.css, light and
           dark sets under the .lyc root. Used as e.g. bg-lyc-paper, text-lyc-ink-strong. */
        lyc: {
          "paper": "var(--paper)",
          "margin": "var(--margin)",
          "sheet": "var(--sheet)",
          "ink": "var(--ink)",
          "ink-strong": "var(--ink-strong)",
          "muted": "var(--muted)",
          "rule": "var(--rule)",
          "rule-soft": "var(--rule-soft)",
          "rule-strong": "var(--rule-strong)",
          "input-bd": "var(--input-bd)",
          "chip": "var(--chip)",
          "hover": "var(--hover)",
          "rail": "var(--rail)",
          "rail-ink": "var(--rail-ink)",
          "rail-on-bg": "var(--rail-on-bg)",
          "rail-on-ink": "var(--rail-on-ink)",
          "lock": "var(--lock)",
          "primary-bg": "var(--primary-bg)",
          "primary-ink": "var(--primary-ink)",
          "scrim": "var(--scrim)",
          "tick": "var(--tick)",
          "seg-empty": "var(--seg-empty)",
          "danger": "var(--danger)",
          "danger-bg": "var(--danger-bg)",
          "focus": "var(--focus)",
          "step": "var(--step)",
          "ok": "var(--ok)",
          "lv0-fill": "var(--lv0-fill)",
          "lv0-bg": "var(--lv0-bg)",
          "lv0-ink": "var(--lv0-ink)",
          "lv0-bd": "var(--lv0-bd)",
          "lv1-fill": "var(--lv1-fill)",
          "lv1-bg": "var(--lv1-bg)",
          "lv1-ink": "var(--lv1-ink)",
          "lv1-bd": "var(--lv1-bd)",
          "lv2-fill": "var(--lv2-fill)",
          "lv2-bg": "var(--lv2-bg)",
          "lv2-ink": "var(--lv2-ink)",
          "lv2-bd": "var(--lv2-bd)",
          "lv3-fill": "var(--lv3-fill)",
          "lv3-bg": "var(--lv3-bg)",
          "lv3-ink": "var(--lv3-ink)",
          "lv3-bd": "var(--lv3-bd)",
          "lv4-fill": "var(--lv4-fill)",
          "lv4-bg": "var(--lv4-bg)",
          "lv4-ink": "var(--lv4-ink)",
          "lv4-bd": "var(--lv4-bd)",
          "cat-math-bg": "var(--cat-math-bg)",
          "cat-math-bd": "var(--cat-math-bd)",
          "cat-math-ink": "var(--cat-math-ink)",
          "cat-rw-bg": "var(--cat-rw-bg)",
          "cat-rw-bd": "var(--cat-rw-bd)",
          "cat-rw-ink": "var(--cat-rw-ink)",
          "cat-review-bg": "var(--cat-review-bg)",
          "cat-review-bd": "var(--cat-review-bd)",
          "cat-review-ink": "var(--cat-review-ink)",
          "cat-test-bg": "var(--cat-test-bg)",
          "cat-test-bd": "var(--cat-test-bd)",
          "cat-test-ink": "var(--cat-test-ink)",
        },
        /* Semantic tokens from CSS variables */
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      boxShadow: {
        '2xs': "var(--shadow-2xs)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        '2xl': "var(--shadow-2xl)",
      },
      transitionDuration: { 150: "150ms", 200: "200ms", 300: "300ms" },
      /* DESIGN.md §1 type scale. Nothing below 14px. */
      fontSize: {
        "lyc-title": ["var(--lyc-text-title)", { lineHeight: "1.15" }],
        "lyc-section": ["var(--lyc-text-section)", { lineHeight: "1.25" }],
        "lyc-panel": ["var(--lyc-text-panel)", { lineHeight: "1.3" }],
        "lyc-body": ["var(--lyc-text-body)", { lineHeight: "1.55" }],
        "lyc-body-lg": ["var(--lyc-text-body-lg)", { lineHeight: "1.55" }],
        "lyc-meta": ["var(--lyc-text-meta)", { lineHeight: "1.45" }],
        "lyc-meta-lg": ["var(--lyc-text-meta-lg)", { lineHeight: "1.45" }],
      },
      fontFamily: {
        sans: "var(--font-sans)",
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
        "lyc-serif": ["var(--lyc-serif)"],
        "lyc-sans": ["var(--lyc-sans)"],
        inter: ['Inter', 'system-ui', 'sans-serif'],
        poppins: ['Poppins', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
