#!/usr/bin/env python3
# @spec [Doc-05A_V1.0, §6 / §12 / §12.4a / §12.5] | @implemented [2026-06-10]
# plain English: the PARITY gate driver. Two subcommands:
#   `gen`   — emit a TEST-ONLY SQL file that (a) creates a fixture-backed
#             canonical_mastery_events over a fixture event table (canonical_mastery_events
#             is Lane C and intentionally NOT in any migration — the parity harness supplies
#             a fixture version), (b) loads all 31 §12 fixtures (events in recency order →
#             strictly-decreasing occurred_at so the global ROW_NUMBER reproduces the
#             intended positions), (c) COPYs the compute_mastery_for_entity output per
#             scenario to STDOUT, and (d) ALSO runs the §12.5 recompute-equivalence check.
#   `check` — read the SQL output (TSV) and assert three-way parity:
#             PL/pgSQL output == Python reference == Doc 05A §12 expected, within the
#             §12.4 tolerances (acc ±1e-6, score ±1e-4, pct ±0.01, level exact).
# expected outcome: any divergence between the PL/pgSQL formula and the independent
#   Python reference (or the §12 table) fails the gate non-zero.
# trade-offs: drives psql via files/STDOUT to avoid adding a python-postgres dependency.
# edge cases: NULL accs/score on cold-start & below-threshold are compared as NULL==NULL.

from __future__ import annotations

import argparse
import os
import sys
import uuid

# import the reference oracle + fixtures (single source of truth for the event sets)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "reference"))
from mastery_reference import FIXTURES, compute_mastery  # noqa: E402

_NS = uuid.UUID("05a05a05-0000-0000-0000-000000000000")  # deterministic fixture namespace


def _student_uuid(fid: str) -> str:
    return str(uuid.uuid5(_NS, f"student:{fid}"))


def _event_uuid(fid: str, idx: int) -> str:
    return str(uuid.uuid5(_NS, f"event:{fid}:{idx}"))


def _sql_lit(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def cmd_gen() -> int:
    """Emit the test-only fixture SQL to stdout."""
    out: list[str] = []
    out.append("-- AUTO-GENERATED by scripts/ci/mastery_parity.py — DO NOT COMMIT as a migration.")
    out.append("-- canonical_mastery_events here is a FIXTURE stand-in (Lane C owns the real one).")
    out.append("SET search_path = public, pg_temp;")
    out.append("""
CREATE TABLE _parity_events (
  student_id uuid NOT NULL, event_id uuid NOT NULL, occurred_at timestamptz NOT NULL,
  source_family text NOT NULL, difficulty smallint NOT NULL, correct boolean NOT NULL,
  section text NOT NULL, domain text NOT NULL, skill text NOT NULL
);""")
    out.append("""
-- The Lane-C migration now ships the PRODUCTION canonical_mastery_events; the isolation harness
-- overrides it with this fixture-backed stand-in (DROP first — RETURNS TABLE shape differs, so
-- CREATE OR REPLACE cannot swap it). This keeps the 31-fixture isolation proof (incl. the
-- test-bearing fixtures that have no production source until WS-4).
DROP FUNCTION IF EXISTS public.canonical_mastery_events(uuid, text, text, text, text);
CREATE FUNCTION public.canonical_mastery_events(
  p_student_id uuid, p_entity_type text, p_section text, p_domain text, p_skill text DEFAULT NULL
) RETURNS TABLE(
  event_id uuid, event_source_kind text, source_family text, section text, domain text, skill text,
  difficulty smallint, correct boolean, occurred_at timestamptz, question_id text
) LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $fn$
  -- column order mirrors Doc 05A §6.2 EXACTLY (matches the production canonical_mastery_events), so
  -- the DROP+CREATE override is positionally identical. event_source_kind/question_id are unused by
  -- the formula but kept for shape parity. question_id is TEXT (SAT id) per SP-21, not uuid.
  SELECT e.event_id, NULL::text AS event_source_kind, e.source_family, e.section, e.domain, e.skill,
         e.difficulty, e.correct, e.occurred_at, NULL::text AS question_id
  FROM public._parity_events e
  WHERE e.student_id = p_student_id
    AND e.section = p_section AND e.domain = p_domain
    AND (p_entity_type = 'domain' OR e.skill = p_skill);
$fn$;""")

    # one student per scenario; events in recency order → occurred_at strictly decreasing.
    base = "2026-01-01T00:00:00Z"
    values: list[str] = []
    for fid, fx in FIXTURES.items():
        sid = _student_uuid(fid)
        for idx, ev in enumerate(fx["events"]):
            eid = _event_uuid(fid, idx)
            # occurred_at = base - idx minutes  → idx 0 (most recent) sorts first under DESC.
            occ = f"(TIMESTAMPTZ {_sql_lit(base)} - (INTERVAL '1 minute' * {idx}))"
            values.append(
                f"({_sql_lit(sid)}, {_sql_lit(eid)}, {occ}, {_sql_lit(ev['source_family'])}, "
                f"{ev['difficulty']}::smallint, {str(ev['correct']).lower()}, 'M', 'd', 's')"
            )
    if values:
        out.append("INSERT INTO _parity_events "
                   "(student_id, event_id, occurred_at, source_family, difficulty, correct, section, domain, skill) VALUES")
        out.append(",\n".join(values) + ";")

    # compute output per scenario, COPYed as TSV (\N for NULL) to STDOUT.
    selects: list[str] = []
    for fid in FIXTURES:
        sid = _student_uuid(fid)
        selects.append(
            f"SELECT {_sql_lit(fid)}::text AS fid, c.total_events, c.acc_test, c.acc_practice, "
            f"c.acc_review, c.mastery_score, c.mastery_pct, c.mastery_level "
            f"FROM public.compute_mastery_for_entity({_sql_lit(sid)}, 'skill', 'M', 'd', 's') c"
        )
    out.append("\\echo __COMPUTE_BEGIN__")
    out.append("COPY (\n" + "\nUNION ALL\n".join(selects) + "\n) TO STDOUT;")
    out.append("\\echo __COMPUTE_END__")

    # §12.5 recompute-equivalence: event-time path is Lane C, so here we assert the
    # recompute path (recompute_skill_mastery, which calls the SAME compute function)
    # equals compute_mastery_for_entity column-for-column. Single-impl ⇒ trivially equal,
    # but we PROVE it executes and agrees (guards against a recompute that forks the math).
    recompute_checks: list[str] = []
    for fid, fx in FIXTURES.items():
        if len(fx["events"]) == 0:
            continue  # recompute on zero events upserts a NULL row; covered by compute path
        sid = _student_uuid(fid)
        recompute_checks.append(
            f"SELECT {_sql_lit(fid)}::text AS fid, "
            f"r.mastery_score IS NOT DISTINCT FROM c.mastery_score "
            f"AND r.mastery_level IS NOT DISTINCT FROM c.mastery_level "
            f"AND r.acc_test IS NOT DISTINCT FROM c.acc_test "
            f"AND r.acc_practice IS NOT DISTINCT FROM c.acc_practice "
            f"AND r.acc_review IS NOT DISTINCT FROM c.acc_review "
            f"AND r.event_count_total = c.total_events AS equal "
            f"FROM public.recompute_skill_mastery({_sql_lit(sid)}, 'M', 'd', 's', false) r "
            f"CROSS JOIN public.compute_mastery_for_entity({_sql_lit(sid)}, 'skill', 'M', 'd', 's') c"
        )
    out.append("\\echo __RECOMPUTE_BEGIN__")
    out.append("COPY (\n" + "\nUNION ALL\n".join(recompute_checks) + "\n) TO STDOUT;")
    out.append("\\echo __RECOMPUTE_END__")

    sys.stdout.write("\n".join(out) + "\n")
    return 0


def _parse_num(tok: str):
    return None if tok == "\\N" else float(tok)


def _close(a, b, tol: float) -> bool:
    if a is None or b is None:
        return a is None and b is None
    return abs(a - b) <= tol


def _extract_block(text: str, begin: str, end: str) -> str:
    lines = text.splitlines()
    try:
        i = lines.index(begin)
        j = lines.index(end)
    except ValueError:
        return ""
    return "\n".join(lines[i + 1:j])


def cmd_check(psql_output: str) -> int:
    compute_tsv = _extract_block(psql_output, "__COMPUTE_BEGIN__", "__COMPUTE_END__")
    recompute_tsv = _extract_block(psql_output, "__RECOMPUTE_BEGIN__", "__RECOMPUTE_END__")
    if not compute_tsv.strip():
        print("PARITY FAIL: no compute output captured (markers missing — did psql error?)")
        return 1
    # parse SQL compute output
    sql_rows: dict[str, dict] = {}
    for line in compute_tsv.splitlines():
        line = line.rstrip("\n")
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) != 8:
            print(f"PARITY FAIL: malformed compute row: {line!r}")
            return 1
        fid = parts[0]
        sql_rows[fid] = {
            "total": int(parts[1]),
            "acc_test": _parse_num(parts[2]),
            "acc_practice": _parse_num(parts[3]),
            "acc_review": _parse_num(parts[4]),
            "score": _parse_num(parts[5]),
            "pct": _parse_num(parts[6]),
            "level": None if parts[7] == "\\N" else int(parts[7]),
        }

    failures: list[str] = []
    if set(sql_rows) != set(FIXTURES):
        missing = set(FIXTURES) - set(sql_rows)
        extra = set(sql_rows) - set(FIXTURES)
        failures.append(f"scenario set mismatch (missing={sorted(missing)} extra={sorted(extra)})")

    for fid, fx in FIXTURES.items():
        if fid not in sql_rows:
            continue
        sql = sql_rows[fid]
        ref = compute_mastery(fx["events"])
        exp = fx["expected"]
        # three-way: SQL vs Python reference, and SQL vs §12 expected.
        triples = [
            ("total", sql["total"], ref["total_events"], exp["total"], 0, True),
            ("acc_test", sql["acc_test"], ref["acc_test"], exp["acc_test"], 1e-6, False),
            ("acc_practice", sql["acc_practice"], ref["acc_practice"], exp["acc_practice"], 1e-6, False),
            ("acc_review", sql["acc_review"], ref["acc_review"], exp["acc_review"], 1e-6, False),
            ("score", sql["score"], ref["mastery_score"], exp["score"], 1e-4, False),
            ("pct", sql["pct"], ref["mastery_pct"], exp["pct"], 1e-2, False),
            ("level", sql["level"], ref["mastery_level"], exp["level"], 0, True),
        ]
        for name, sval, rval, eval_, tol, exact in triples:
            if exact:
                ok = (sval == rval) and (sval == eval_)
            else:
                ok = _close(sval, rval, tol) and _close(sval, eval_, tol)
            if not ok:
                failures.append(
                    f"{fid}.{name}: sql={sval} reference={rval} spec_expected={eval_} (tol={tol})"
                )

    # recompute-equivalence (§12.5)
    for line in recompute_tsv.splitlines():
        line = line.rstrip("\n")
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) != 2:
            failures.append(f"malformed recompute row: {line!r}")
            continue
        fid, equal = parts[0], parts[1]
        if equal != "t":
            failures.append(f"{fid}: recompute_skill_mastery != compute_mastery_for_entity (§12.5 equivalence broken)")

    if failures:
        print(f"PARITY GATE FAILED — {len(failures)} divergence(s):")
        for f in failures:
            print("  - " + f)
        return 1
    print(f"PARITY GATE PASSED — all {len(FIXTURES)} fixtures bit-exact three-way "
          f"(PL/pgSQL == Python reference == Doc 05A §12), recompute-equivalence holds.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Doc 05A mastery parity gate driver")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("gen", help="emit fixture-load + compute SQL to stdout")
    cp = sub.add_parser("check", help="compare SQL output three-way")
    cp.add_argument("--psql-out", required=True, help="path to captured psql stdout")
    args = ap.parse_args()
    if args.cmd == "gen":
        return cmd_gen()
    with open(args.psql_out, encoding="utf-8") as fh:
        psql_output = fh.read()
    return cmd_check(psql_output)


if __name__ == "__main__":
    sys.exit(main())
