#!/usr/bin/env bash
# ============================================================================
# Scoring evidence packet check — the repo-hosted v1.0 packet is the attested one
# ============================================================================
# @spec [Doc-04B_V4.3, §7.2 (validation_packet_sha256 / _url), §18.2,
#        Appendix B ("SHA-256 of the concatenated file contents, taken in
#        sorted-full-path order")] | @implemented [2026-09-24]
#   OWNER RULING 2026-09-24: the packet is repo-hosted at
#   scripts/ci/fixtures/scoring-v1.0 and is v1.0's validation_packet_url.
#
# plain English: proves, from the committed bytes alone, that
#   P1 the six packet files hash to 29c3e0fd… — the value stored in
#      scoring_model_versions.validation_packet_sha256 — computed two ways:
#      (a) shell: sha256 of the files concatenated in C-locale sorted order of
#          their packet-relative paths, and (b) the packet's own
#          compute_packet_hash(), which sorts ABSOLUTE paths. All six files
#          share one directory prefix, so sorting absolute paths and sorting the
#          relative paths byte-wise give the same order — (a) is the
#          location-independent statement of (b);
#   P2 the evidence_packet.sha256 file names the same hash;
#   P3 the committed validation_sweep.py is byte-identical to the locked spec
#      copy in docs/Spec (the spec's copy is the canonical reference);
#   P4 re-running validation_sweep.py in a scratch copy reproduces every
#      generated file byte-for-byte (the packet is not hand-edited).
#   The CSVs are CRLF (Python csv default); .gitattributes marks the packet
#   -text so git never normalises the hashed bytes.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
PKT="$ROOT/scripts/ci/fixtures/scoring-v1.0"
SPEC_PY="$ROOT/docs/Spec/Doc 04B Full length scoring V4.3/validation_sweep.py"
EXPECTED=29c3e0fd362b6f5c3c90c50a49b49fa55ebc03e1518f8ab1922408329b88651b
FILES="source_snapshot/extraction_notes.md test_ninjas_bands_reference.csv validation_results.csv validation_summary.md validation_sweep.py validation_targeted_fixtures.csv"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
FAIL=0

# P1a — location-independent: relative paths, C-locale byte order.
ORDER="$(printf '%s\n' $FILES | LC_ALL=C sort)"
SHELL_HASH="$(cd "$PKT" && cat $ORDER | sha256sum | cut -d' ' -f1)"
# P1b — the packet's own function over absolute paths.
PY_HASH="$(cd "$PKT" && PYTHONDONTWRITEBYTECODE=1 python3 -c "
import os, sys
sys.path.insert(0, '.')
import validation_sweep as v
print(v.compute_packet_hash([os.path.abspath(f) for f in sys.argv[1:]]))
" $FILES)"
if [ "$SHELL_HASH" = "$EXPECTED" ] && [ "$PY_HASH" = "$EXPECTED" ]; then
  echo "ok   [P1 packet-hash] sha256(concat in sorted order) = compute_packet_hash() = $EXPECTED"
  echo "     order: $(echo $ORDER)"
else
  echo "FAIL [P1 packet-hash]: shell=$SHELL_HASH python=$PY_HASH expected=$EXPECTED"; FAIL=1
fi

# P2 — the hash file agrees.
if [ "$(tail -n 1 "$PKT/evidence_packet.sha256")" = "$EXPECTED" ]; then
  echo "ok   [P2 hash-file] evidence_packet.sha256 names $EXPECTED"
else
  echo "FAIL [P2 hash-file]: evidence_packet.sha256 last line is '$(tail -n 1 "$PKT/evidence_packet.sha256")'"; FAIL=1
fi

# P3 — the reference implementation is the spec's, byte for byte.
if cmp -s "$PKT/validation_sweep.py" "$SPEC_PY"; then
  echo "ok   [P3 sweep-matches-spec] validation_sweep.py is byte-identical to docs/Spec"
else
  echo "FAIL [P3 sweep-matches-spec]: scripts/ci/fixtures/scoring-v1.0/validation_sweep.py differs from docs/Spec"; FAIL=1
fi

# P4 — regenerate in scratch and compare every generated file.
mkdir -p "$WORK/source_snapshot"
cp "$PKT/validation_sweep.py" "$WORK/"
cp "$PKT/source_snapshot/extraction_notes.md" "$WORK/source_snapshot/"
(cd "$WORK" && PYTHONDONTWRITEBYTECODE=1 python3 validation_sweep.py >/dev/null)
REGEN_BAD=""
for f in validation_results.csv test_ninjas_bands_reference.csv validation_summary.md validation_targeted_fixtures.csv evidence_packet.sha256; do
  cmp -s "$PKT/$f" "$WORK/$f" || REGEN_BAD="$REGEN_BAD $f"
done
if [ -z "$REGEN_BAD" ]; then
  echo "ok   [P4 packet-regenerates] validation_sweep.py reproduces all generated files byte-for-byte"
else
  echo "FAIL [P4 packet-regenerates]: regenerated bytes differ:$REGEN_BAD"; FAIL=1
fi

[ "$FAIL" = 0 ] || { echo "SCORING EVIDENCE PACKET: FAIL"; exit 1; }
echo "SCORING EVIDENCE PACKET: PASS (4 checks)"
