/**
 * Lyceon Ingestion v3 - Core Types
 * 
 * Defines all interfaces for the ingestion pipeline:
 * - QuestionDoc: Final question format for Supabase
 * - QuestionDocDraft: Intermediate draft during extraction
 * - OutsideSchema: Per-PDF schema generated by LLM
 */

export interface DocAiEntityDefinition {
  name: string;
  displayName: string;
  valueType: "string" | "number";
  occurrence: "REQUIRED" | "OPTIONAL" | "REPEATED";
  children?: DocAiEntityDefinition[];
  hints?: string[];
}

export interface OutsideSchema {
  documentType: string;
  entities: DocAiEntityDefinition[];
  layoutHeuristics: {
    questionNumberPattern?: string;
    optionPrefixPattern?: string;
    answerKeyPattern?: string;
    multiPageThresholdLines?: number;
  };
}

export interface QuestionOption {
  key: "A" | "B" | "C" | "D";
  text: string;
}

export interface QuestionDocDraft {
  draftId: string;
  stem: string | null;
  options: QuestionOption[] | null;
  answer: "A" | "B" | "C" | "D" | null;
  sourcePages: number[];
  sourcePdfPath: string;
  backendSource: "docai" | "vision";
  rawBlocks: string[];
  notes?: string[];
}

export interface QuestionCompetency {
  code: string;
  raw: string | null;
}

export interface QuestionDoc {
  canonicalId: string;
  testCode: string;
  sectionCode: string;
  sourceType: 1 | 2;
  version: number;
  stem: string;
  options: QuestionOption[];
  answer: "A" | "B" | "C" | "D" | null;
  explanation: string;
  difficulty: string | null;
  competencies: QuestionCompetency[];
  satQuestionNumber: string | null;
  sourcePages: number[];
  sourcePdfPath: string;
  createdAt: string;
  updatedAt: string;
}

export type QAStatus = "GOOD" | "NEEDS_VISION_FALLBACK" | "REJECT_HARD";

export interface QAPassResult {
  draftId: string;
  status: QAStatus;
  repairedStem: string | null;
  repairedOptions: QuestionOption[] | null;
  filledMetadata: {
    difficulty?: string | null;
    competencies?: QuestionCompetency[];
  };
  rejectionReason?: string;
}

export interface QAReconcileResult {
  status: "ACCEPTED" | "REJECTED";
  finalQuestion?: QuestionDoc;
  rejectionReason?: string;
}

export interface QuestionVisionExtract {
  stem: string;
  options: QuestionOption[];
  answer: "A" | "B" | "C" | "D" | null;
}

export interface IngestionJobMetrics {
  totalDocAiDrafts: number;
  docAiGoodCount: number;
  needsVisionFallbackCount: number;
  visionUsedCount: number;
  finalAcceptedCount: number;
  finalRejectedCount: number;
  timings: {
    schemaGenerationMs?: number;
    docaiMs?: number;
    parseMs?: number;
    qa1Ms?: number;
    visionMs?: number;
    qa2Ms?: number;
    totalMs?: number;
  };
}

export interface IngestionJob {
  id: string;
  pdfPath: string;
  testCode: string;
  sectionCode: string;
  status: "pending" | "processing" | "completed" | "failed";
  outsideSchema?: OutsideSchema;
  metrics?: IngestionJobMetrics;
  error?: string;
  createdAt: string;
  updatedAt: string;
}
